const el=document.getElementById('app');
let state=null,auth=null,actor=localStorage.getItem('planner-profile')||'',viewProfile=localStorage.getItem('planner-view')||'all',editing=0,status='',saving=false,personalEdit='';
const mealLabels={breakfast:'Desayuno',lunch:'Comida',dinner:'Cena'},mealIcons={breakfast:'☀️',lunch:'🍽️',dinner:'🌙'};
const pantryCategories=['Despensa','Nevera','Congelador','Fruta y verdura','Bebidas','Limpieza','Otros'];
const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const id=()=>crypto.randomUUID(); const norm=s=>String(s||'').trim().toLowerCase();
function initials(n='Familia'){return n.trim().split(/\s+/).slice(0,2).map(x=>x[0]?.toUpperCase()||'').join('')||'F'}
function monday(offset=0){const d=new Date(),day=d.getDay()||7;d.setHours(12,0,0,0);d.setDate(d.getDate()-day+1+offset*7);return d}
function dateAt(i){const d=monday(state?.weekOffset||0);d.setDate(d.getDate()+i);return d}
function fmt(d){return new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'short'}).format(d)}
function weekLabel(){const a=monday(state.weekOffset||0),b=new Date(a);b.setDate(a.getDate()+6);return `${fmt(a)} — ${fmt(b)}`}
function normalize(s={}){
  const profiles=Array.isArray(s.profiles)?s.profiles:[];
  const days=(s.days||[]).map(d=>{const n={...d};for(const k of Object.keys(mealLabels)){const old=d[k]||{};n[k]={text:old.text||'',done:!!old.done,people:old.people&&typeof old.people==='object'?old.people:{}}}return n});
  let shopping=Array.isArray(s.shopping)?s.shopping.filter(x=>!x.done):[];
  const pantry=[];
  for(const x of (Array.isArray(s.pantry)?s.pantry:[])){
    if((x.level||'ok')==='out'){
      if(!shopping.some(y=>norm(y.text)===norm(x.text)))shopping=[...shopping,{id:id(),text:x.text,done:false}];
      continue;
    }
    const parsed=parseInt(x.count??x.quantity,10); pantry.push({...x,count:Number.isFinite(parsed)&&parsed>0?parsed:1,level:x.level==='low'?'low':'ok'});
  }
  return {...s,days,shopping,pantry,profiles,history:Array.isArray(s.history)?s.history:[]};
}
async function api(url,opt){const r=await fetch(url,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw Object.assign(new Error(d.error||'Error'),{status:r.status});return d}
function isEditing(){const a=document.activeElement;return saving||Date.now()-editing<2200||!!(a&&['INPUT','TEXTAREA','SELECT'].includes(a.tagName))}
async function check(){try{auth=(await api('/api/check')).ok;if(auth)await load()}catch{auth=false}render()}
async function load(quiet=false){if(quiet&&isEditing())return;try{const d=normalize(await api('/api/planner'));if(!isEditing()){state=d;render()}}catch(e){if(e.status===401){auth=false;render()}else if(!quiet){status=e.message;render()}}}
function who(){return state?.profiles?.find(p=>p.id===actor)?.name||'Familia Laviña Pérez'}
function stamp(action){return {id:id(),actor:who(),action,at:new Date().toISOString()}}
async function save(next,action='actualizó la aplicación'){editing=Date.now();saving=true;state=normalize({...next,history:[stamp(action),...(next.history||state?.history||[])].slice(0,50)});status='Guardando…';render();try{state=normalize(await api('/api/planner',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...state,updatedBy:who()})}));status='Guardado ✓';render();setTimeout(()=>{status='';saving=false;render()},650)}catch(e){saving=false;status='Error al guardar: '+e.message;render()}}
function profileName(pid){return state.profiles.find(p=>p.id===pid)?.name||'Perfil'}
function ownMeal(meal,pid){return meal.people?.[pid]||null}
function mealDone(meal,pid){if(pid==='all')return !!meal.done;const own=ownMeal(meal,pid);return own?!!own.done:!!meal.done}
function relative(iso){const n=Date.now()-new Date(iso).getTime(),m=Math.floor(n/60000);if(m<1)return'ahora';if(m<60)return`hace ${m} min`;const h=Math.floor(m/60);if(h<24)return`hace ${h} h`;return new Date(iso).toLocaleDateString('es-ES',{day:'numeric',month:'short'})}
function profilePicker(){
  const cards=[`<button class="profile-card ${actor===''?'selected':''}" data-actor=""><span class="avatar family-avatar">FLP</span><strong>Familia</strong><small>Comida común</small></button>`,...state.profiles.map(p=>`<button class="profile-card ${actor===p.id?'selected':''}" data-actor="${p.id}"><span class="avatar">${esc(initials(p.name))}</span><strong>${esc(p.name)}</strong><small>${actor===p.id?'Perfil activo':'Elegir perfil'}</small></button>`)].join('');
  return `<section class="profile-zone"><div class="profile-zone-head"><div><p class="eyebrow">¿QUIÉN ESTÁ USANDO LA APP?</p><h3>${actor?`Hola, ${esc(profileName(actor))}`:'Elegid vuestro perfil'}</h3></div><form id="profileForm" class="profile-add"><input id="profileName" placeholder="Nuevo perfil"><button>＋</button></form></div><div class="profile-stream">${cards}</div></section>`;
}
function renderMeal(d,i,k){
  const meal=d[k],pid=viewProfile,isAll=pid==='all',own=isAll?null:ownMeal(meal,pid),done=mealDone(meal,pid),common=meal.text||'',key=`${i}:${k}:${pid}`,editingPersonal=personalEdit===key;
  if(isAll){return `<div class="meal ${done?'done':''}"><div class="meal-title"><span>${mealIcons[k]}</span><b>${mealLabels[k]}</b><em>Para todos</em></div><textarea data-meal="${key}" placeholder="Escribe la comida común…">${esc(common)}</textarea><button class="check" data-check="${key}">✓</button>${state.profiles.filter(p=>meal.people?.[p.id]?.text).map(p=>`<div class="override-chip">${esc(p.name)}: ${esc(meal.people[p.id].text)}</div>`).join('')}</div>`}
  if(own?.text||editingPersonal){return `<div class="meal ${done?'done':''}"><div class="meal-title"><span>${mealIcons[k]}</span><b>${mealLabels[k]}</b><em>${esc(profileName(pid))}</em></div>${common?`<div class="commonhint">Comida común: <strong>${esc(common)}</strong></div>`:''}<textarea data-meal="${key}" data-personal="1" placeholder="¿Qué come ${esc(profileName(pid))}?">${esc(own?.text||'')}</textarea><div class="meal-actions"><button class="usecommon" data-common="${key}">↩ Comida común</button><button class="check inline-check" data-check="${key}">✓</button></div></div>`}
  return `<div class="meal simple-meal ${done?'done':''}"><div class="meal-title"><span>${mealIcons[k]}</span><b>${mealLabels[k]}</b><em>${esc(profileName(pid))}</em></div><div class="common-display">${common?`<span>Come lo mismo:</span><strong>${esc(common)}</strong>`:'<span>No hay comida común todavía</span>'}</div><button class="different" data-different="${key}">＋ Yo como otra cosa</button></div>`;
}
function render(){
  if(auth===null)return;if(!auth)return renderLogin();if(!state)return el.innerHTML='<div class="center"><div class="spinner"></div></div>';state=normalize(state);
  if(actor&&!state.profiles.some(p=>p.id===actor)){actor='';localStorage.removeItem('planner-profile')}
  if(viewProfile!=='all'&&!state.profiles.some(p=>p.id===viewProfile)){viewProfile='all';localStorage.setItem('planner-view','all')}
  const list=state.shopping.map(x=>`<div class="shopitem"><button class="shop-ok" data-shopcheck="${x.id}" title="Comprado">✓</button><input data-shoptext="${x.id}" value="${esc(x.text)}"><button class="trash" data-trash="${x.id}" title="Quitar">✕</button></div>`).join('');
  const pantry=state.pantry.map(x=>`<div class="pantryitem"><div class="pantry-main"><input class="pantry-name" data-pantrytext="${x.id}" value="${esc(x.text)}"><span class="pantry-meta">${esc(x.category||'Despensa')}</span></div><select data-pantrycat="${x.id}">${pantryCategories.map(c=>`<option ${c===(x.category||'Despensa')?'selected':''}>${esc(c)}</option>`).join('')}</select><div class="stepper"><button data-minus="${x.id}">−</button><strong>${x.count||1}</strong><button data-plus="${x.id}">＋</button></div><button class="stock ${x.level==='low'?'low':'ok'}" data-stock="${x.id}">${x.level==='low'?'Queda poco':'Hay'}</button><button class="ranout" data-ranout="${x.id}">Se acabó →</button></div>`).join('');
  const days=state.days.map((d,i)=>{const dt=dateAt(i);return `<article class="day"><div class="dayhead"><div><span>${esc(d.name)}</span><strong>${dt.getDate()}</strong></div><small>${dt.toLocaleDateString('es-ES',{month:'short'})}</small></div>${Object.keys(mealLabels).map(k=>renderMeal(d,i,k)).join('')}<input class="note" data-note="${i}" value="${esc(d.note||'')}" placeholder="Nota del día…"></article>`}).join('');
  const tabs=`<button class="${viewProfile==='all'?'active':''}" data-view="all">Todos</button>${state.profiles.map(p=>`<button class="${viewProfile===p.id?'active':''}" data-view="${p.id}">${esc(p.name)}</button>`).join('')}`;
  const history=state.history.slice(0,8).map(h=>`<div class="historyitem"><strong>${esc(h.actor)}</strong><span>${esc(h.action)}</span><small>${relative(h.at)}</small></div>`).join('')||'<p class="empty">Todavía no hay cambios.</p>';
  el.innerHTML=`<main class="shell"><header class="top compact-top"><div><p class="eyebrow">FAMILIA LAVIÑA PÉREZ</p><h1>Comemos juntos,<br><em>a nuestra manera.</em></h1></div><button id="logout" class="icon">↪</button></header>${profilePicker()}<nav class="navchips"><a href="#compra">Compra</a><a href="#despensa">Despensa</a><a href="#planning">Planning</a><a href="#actividad">Actividad</a></nav><div class="sync">${esc(status||`Sincronizado · última edición ${state.updatedBy||'Familia Laviña Pérez'}`)}</div>
  <section id="compra" class="shopping first"><div class="intro"><div class="bubble">🛒</div><p class="eyebrow">LISTA DE LA COMPRA</p><h2>Comprar y listo.</h2><p>✓ = comprado y vuelve a Despensa. ✕ = simplemente quitar de la lista.</p></div><div class="listcard"><div class="listhead"><h3>Lista de la compra</h3><span>${state.shopping.length} pendientes</span></div>${list||'<p class="empty">No hay nada pendiente.</p>'}<div class="add"><input id="newItem" placeholder="Añadir producto…"><button id="add">＋</button></div></div></section>
  <section id="despensa" class="pantry-section"><div class="pantry-hero"><div class="bubble pantrybubble">🥫</div><div><p class="eyebrow">DESPENSA</p><h2>Solo lo que hay en casa.</h2><p>Usa − / + para la cantidad. Si pulsas “Se acabó”, desaparece de aquí y pasa directamente a Compra.</p></div><div class="pantry-stats"><div><strong>${state.pantry.length}</strong><span>Productos</span></div><div><strong>${state.pantry.filter(x=>x.level==='low').length}</strong><span>Queda poco</span></div></div></div><div class="pantrycard"><div class="listhead"><h3>Despensa</h3><span>${state.pantry.reduce((a,x)=>a+(x.count||1),0)} uds.</span></div>${pantry||'<p class="empty">Ahora mismo no hay productos registrados.</p>'}<div class="pantryadd"><input id="newPantry" placeholder="Ej. Leche, arroz, café…"><select id="newPantryCat">${pantryCategories.map(c=>`<option>${esc(c)}</option>`).join('')}</select><button id="addPantry">＋ Añadir</button></div></div></section>
  <section id="planning" class="planningWrap"><div class="week"><button id="prev">← anterior</button><div><span>SEMANA</span><strong>${weekLabel()}</strong></div><button id="next">siguiente →</button></div><div class="profileView"><div><p class="eyebrow">MENÚ DE</p><div class="profiletabs">${tabs}</div></div><p>${viewProfile==='all'?'Editas la comida común de la familia.':`Ves el menú de ${esc(profileName(viewProfile))}. Si come lo mismo, no haces nada. Si no, pulsa “Yo como otra cosa”.`}</p></div><div class="days">${days}</div></section>
  <section id="actividad" class="activity"><div><p class="eyebrow">ACTIVIDAD</p><h2>Quién cambió qué</h2></div><div class="historycard">${history}</div></section><footer>Familia Laviña Pérez · compra, despensa y planning</footer></main>`;bind();
}
function renderLogin(){el.innerHTML=`<main class="loginPage"><section class="login"><div class="lock">🔒</div><p class="eyebrow">FAMILIA LAVIÑA PÉREZ</p><h1>Organización familiar</h1><p class="sub">Compra, despensa y planning compartidos.</p><form id="loginForm"><label>Contraseña familiar</label><input id="password" type="password" placeholder="••••••••••" autofocus><p id="err" class="error"></p><button class="primary">Entrar</button></form></section></main>`;document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();const err=document.getElementById('err');err.textContent='';try{await api('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:document.getElementById('password').value})});auth=true;state=null;render();await load()}catch(x){err.textContent=x.message}}}
function moveToShopping(item,action){const exists=state.shopping.some(x=>norm(x.text)===norm(item.text));const shopping=exists?state.shopping:[...state.shopping,{id:id(),text:item.text,done:false}];const pantry=state.pantry.filter(x=>x.id!==item.id);save({...state,shopping,pantry},action)}
function bind(){
  document.querySelectorAll('[data-actor]').forEach(b=>b.onclick=()=>{actor=b.dataset.actor;viewProfile=actor||'all';localStorage.setItem('planner-profile',actor);localStorage.setItem('planner-view',viewProfile);render()});
  document.getElementById('profileForm').onsubmit=e=>{e.preventDefault();const t=document.getElementById('profileName'),name=t.value.trim();if(!name)return;if(state.profiles.some(p=>norm(p.name)===norm(name))){status='Ese perfil ya existe';render();return}const p={id:id(),name};actor=p.id;viewProfile=p.id;localStorage.setItem('planner-profile',actor);localStorage.setItem('planner-view',viewProfile);save({...state,profiles:[...state.profiles,p]},`creó el perfil ${name}`)};
  document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{viewProfile=b.dataset.view;localStorage.setItem('planner-view',viewProfile);personalEdit='';render()});
  document.getElementById('logout').onclick=async()=>{await api('/api/logout',{method:'POST'});auth=false;state=null;render()};
  document.getElementById('prev').onclick=()=>save({...state,weekOffset:(state.weekOffset||0)-1},'cambió de semana');document.getElementById('next').onclick=()=>save({...state,weekOffset:(state.weekOffset||0)+1},'cambió de semana');
  document.querySelectorAll('[data-different]').forEach(b=>b.onclick=()=>{personalEdit=b.dataset.different;render();setTimeout(()=>document.querySelector(`[data-meal="${CSS.escape(personalEdit)}"]`)?.focus(),0)});
  document.querySelectorAll('[data-meal]').forEach(t=>{t.oninput=()=>editing=Date.now();t.onblur=()=>{const [i,k,pid]=t.dataset.meal.split(':'),val=t.value.trim();const old=pid==='all'?(state.days[i][k].text||''):(state.days[i][k].people?.[pid]?.text||'');if(val===old){personalEdit='';return}const days=state.days.map((d,j)=>{if(j!=i)return d;const m=d[k];if(pid==='all')return {...d,[k]:{...m,text:val}};const people={...m.people};if(!val)delete people[pid];else people[pid]={...(people[pid]||{}),text:val,done:people[pid]?.done??m.done};return {...d,[k]:{...m,people}}});personalEdit='';save({...state,days},`cambió ${mealLabels[k].toLowerCase()} del ${state.days[i].name}${pid==='all'?' para todos':' para '+profileName(pid)}`)}});
  document.querySelectorAll('[data-common]').forEach(b=>b.onclick=()=>{const [i,k,pid]=b.dataset.common.split(':');const days=state.days.map((d,j)=>{if(j!=i)return d;const m=d[k],people={...m.people};delete people[pid];return {...d,[k]:{...m,people}}});personalEdit='';save({...state,days},`${profileName(pid)} vuelve a la comida común del ${state.days[i].name}`)});
  document.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>{const [i,k,pid]=b.dataset.check.split(':');const days=state.days.map((d,j)=>{if(j!=i)return d;const m=d[k];if(pid==='all')return {...d,[k]:{...m,done:!m.done}};const own=m.people?.[pid]||{};return {...d,[k]:{...m,people:{...m.people,[pid]:{text:own.text||'',done:!mealDone(m,pid)}}}}});save({...state,days},`marcó ${mealLabels[k].toLowerCase()} del ${state.days[i].name}`)});
  document.querySelectorAll('[data-note]').forEach(t=>{t.oninput=()=>editing=Date.now();t.onblur=()=>{const i=+t.dataset.note;if(t.value===state.days[i].note)return;const days=state.days.map((d,j)=>j===i?{...d,note:t.value}:d);save({...state,days},`cambió la nota del ${state.days[i].name}`)}});
  document.querySelectorAll('[data-shopcheck]').forEach(b=>b.onclick=()=>{const item=state.shopping.find(x=>x.id===b.dataset.shopcheck);if(!item)return;const existing=state.pantry.find(x=>norm(x.text)===norm(item.text));const pantry=existing?state.pantry.map(x=>x.id===existing.id?{...x,count:(x.count||1)+1,level:'ok'}:x):[...state.pantry,{id:id(),text:item.text,category:'Despensa',count:1,level:'ok'}];save({...state,shopping:state.shopping.filter(x=>x.id!==item.id),pantry},`compró ${item.text} y lo guardó en despensa`)});
  document.querySelectorAll('[data-shoptext]').forEach(t=>{t.oninput=()=>editing=Date.now();t.onblur=()=>{const old=state.shopping.find(x=>x.id===t.dataset.shoptext)?.text||'';if(t.value===old)return;save({...state,shopping:state.shopping.map(x=>x.id===t.dataset.shoptext?{...x,text:t.value}:x)},'editó la lista de la compra')}});
  document.querySelectorAll('[data-trash]').forEach(b=>b.onclick=()=>save({...state,shopping:state.shopping.filter(x=>x.id!==b.dataset.trash)},'quitó un producto de la compra'));
  const add=()=>{const t=document.getElementById('newItem'),text=t.value.trim();if(!text)return;if(state.shopping.some(x=>norm(x.text)===norm(text))){status='Ya está en la lista';render();return}save({...state,shopping:[...state.shopping,{id:id(),text,done:false}]},`añadió ${text} a la compra`)};document.getElementById('add').onclick=add;document.getElementById('newItem').onkeydown=e=>{if(e.key==='Enter')add()};
  document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>{const item=state.pantry.find(x=>x.id===b.dataset.minus);if(!item)return;const n=(item.count||1)-1;if(n<=0)return moveToShopping(item,`${item.text} se acabó y pasó a la compra`);save({...state,pantry:state.pantry.map(x=>x.id===item.id?{...x,count:n}:x)},`redujo ${item.text} a ${n}`)});
  document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>{const item=state.pantry.find(x=>x.id===b.dataset.plus);save({...state,pantry:state.pantry.map(x=>x.id===item.id?{...x,count:(x.count||1)+1,level:'ok'}:x)},`aumentó ${item.text}`)});
  document.querySelectorAll('[data-stock]').forEach(b=>b.onclick=()=>{const item=state.pantry.find(x=>x.id===b.dataset.stock);save({...state,pantry:state.pantry.map(x=>x.id===item.id?{...x,level:x.level==='low'?'ok':'low'}:x)},`actualizó ${item.text}`)});
  document.querySelectorAll('[data-ranout]').forEach(b=>b.onclick=()=>{const item=state.pantry.find(x=>x.id===b.dataset.ranout);if(item)moveToShopping(item,`${item.text} se acabó y pasó a la compra`)});
  document.querySelectorAll('[data-pantrytext]').forEach(t=>{t.oninput=()=>editing=Date.now();t.onblur=()=>{const item=state.pantry.find(x=>x.id===t.dataset.pantrytext);if(!item||item.text===t.value)return;save({...state,pantry:state.pantry.map(x=>x.id===item.id?{...x,text:t.value}:x)},'editó un producto de despensa')}});
  document.querySelectorAll('[data-pantrycat]').forEach(t=>t.onchange=()=>save({...state,pantry:state.pantry.map(x=>x.id===t.dataset.pantrycat?{...x,category:t.value}:x)},'cambió una categoría'));
  const addPantry=()=>{const t=document.getElementById('newPantry'),c=document.getElementById('newPantryCat'),text=t.value.trim();if(!text)return;const ex=state.pantry.find(x=>norm(x.text)===norm(text));if(ex)return save({...state,pantry:state.pantry.map(x=>x.id===ex.id?{...x,count:(x.count||1)+1,level:'ok'}:x)},`añadió otra unidad de ${text}`);save({...state,pantry:[...state.pantry,{id:id(),text,category:c.value,count:1,level:'ok'}]},`añadió ${text} a despensa`)};document.getElementById('addPantry').onclick=addPantry;document.getElementById('newPantry').onkeydown=e=>{if(e.key==='Enter')addPantry()};
}
check();setInterval(()=>{if(auth&&state&&!isEditing())load(true)},10000);
