const el=document.getElementById('app');let state=null,auth=null,actor=localStorage.getItem('planner-profile')||'',viewProfile=localStorage.getItem('planner-view')||'all',editing=0,status='';
const mealLabels={breakfast:'Desayuno',lunch:'Comida',dinner:'Cena'},mealIcons={breakfast:'☀️',lunch:'🍽️',dinner:'🌙'};
const pantryCategories=['Despensa','Nevera','Congelador','Fruta y verdura','Bebidas','Limpieza','Otros'];
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function id(){return crypto.randomUUID()}function monday(offset=0){const d=new Date(),day=d.getDay()||7;d.setHours(12,0,0,0);d.setDate(d.getDate()-day+1+offset*7);return d}function dateAt(i){const d=monday(state?.weekOffset||0);d.setDate(d.getDate()+i);return d}function fmt(d){return new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'short'}).format(d)}function weekLabel(){const a=monday(state.weekOffset||0),b=new Date(a);b.setDate(a.getDate()+6);return `${fmt(a)} — ${fmt(b)}`}
function normalize(s){const profiles=Array.isArray(s.profiles)?s.profiles:[];const days=(s.days||[]).map(d=>{const n={...d};for(const k of Object.keys(mealLabels)){const old=d[k]||{text:'',done:false};n[k]={text:old.text||'',done:!!old.done,people:old.people&&typeof old.people==='object'?old.people:{}}}return n});return {...s,days,shopping:Array.isArray(s.shopping)?s.shopping:[],pantry:Array.isArray(s.pantry)?s.pantry:[],profiles,history:Array.isArray(s.history)?s.history:[]}}
async function api(url,opt){const r=await fetch(url,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw Object.assign(new Error(d.error||'Error'),{status:r.status});return d}
async function check(){try{auth=(await api('/api/check')).ok;if(auth)await load()}catch{auth=false}render()}
async function load(quiet=false){try{const d=normalize(await api('/api/planner'));if(Date.now()-editing>2200){state=d;render()}}catch(e){if(e.status===401){auth=false;render()}else if(!quiet){status=e.message;render()}}}
function who(){return actor||'Familia Laviña Pérez'}function stamp(action){return {id:id(),actor:who(),action,at:new Date().toISOString()}}
async function save(next,action='actualizó la aplicación'){state=normalize({...next,history:[stamp(action),...(next.history||state?.history||[])].slice(0,40)});editing=Date.now();status='Guardando…';render();try{state=normalize(await api('/api/planner',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...state,updatedBy:who()})}));status='Guardado ✓';render();setTimeout(()=>{status='';render()},1400)}catch(e){status=e.message;render()}}
function pantryBadge(level){return level==='low'?'Queda poco':level==='out'?'Falta':'Hay'}
function mealValue(meal,pid){if(pid==='all')return meal.text||'';return meal.people?.[pid]?.text??meal.text??''}function mealDone(meal,pid){if(pid==='all')return !!meal.done;return meal.people?.[pid]?.done??meal.done??false}function profileName(pid){return state.profiles.find(p=>p.id===pid)?.name||'Perfil'}
function relative(iso){const n=Date.now()-new Date(iso).getTime(),m=Math.floor(n/60000);if(m<1)return'ahora';if(m<60)return`hace ${m} min`;const h=Math.floor(m/60);if(h<24)return`hace ${h} h`;return new Date(iso).toLocaleDateString('es-ES',{day:'numeric',month:'short'})}
function profileControls(){const opts=state.profiles.map(p=>`<option value="${p.id}" ${actor===p.id?'selected':''}>${esc(p.name)}</option>`).join('');return `<div class="profilebox"><label>Estoy usando la app como<select id="actor"><option value="">Familia</option>${opts}</select></label><div class="addprofile"><input id="profileName" placeholder="Nuevo perfil…"><button id="addProfile">＋</button></div></div>`}
function renderMeal(d,i,k){const meal=d[k],pid=viewProfile,done=mealDone(meal,pid),value=mealValue(meal,pid),tag=pid==='all'?'Para todos':profileName(pid);const overrides=pid==='all'?state.profiles.filter(p=>meal.people?.[p.id]?.text).map(p=>`<span>${esc(p.name)}: ${esc(meal.people[p.id].text)}</span>`).join(''):'';return `<div class="meal ${done?'done':''}"><div class="meal-title"><span>${mealIcons[k]}</span><b>${mealLabels[k]}</b><em>${esc(tag)}</em></div><textarea data-meal="${i}:${k}:${pid}">${esc(value)}</textarea><button class="check" data-check="${i}:${k}:${pid}">✓</button>${overrides?`<div class="overrides">${overrides}</div>`:''}</div>`}
function render(){if(auth===null)return;if(!auth)return renderLogin();if(!state)return el.innerHTML='<div class="center"><div class="spinner"></div></div>';state=normalize(state);if(actor&&!state.profiles.some(p=>p.id===actor)){actor='';localStorage.removeItem('planner-profile')}if(viewProfile!=='all'&&!state.profiles.some(p=>p.id===viewProfile)){viewProfile='all'};
const list=state.shopping.map(x=>`<div class="shopitem ${x.done?'done':''}"><button data-shopcheck="${x.id}">✓</button><input data-shoptext="${x.id}" value="${esc(x.text)}"><button class="trash" data-trash="${x.id}">✕</button></div>`).join('');
const pantry=state.pantry.map(x=>`<div class="pantryitem level-${esc(x.level||'ok')}"><div class="pantry-main"><input class="pantry-name" data-pantrytext="${x.id}" value="${esc(x.text)}"><span class="pantry-meta">${esc(x.category||'Despensa')}${x.quantity?` · ${esc(x.quantity)}`:''}</span></div><select data-pantrycat="${x.id}">${pantryCategories.map(c=>`<option ${c===(x.category||'Despensa')?'selected':''}>${esc(c)}</option>`).join('')}</select><input class="qty" data-pantryqty="${x.id}" value="${esc(x.quantity||'')}" placeholder="Cantidad"><button class="stock ${x.level||'ok'}" data-stock="${x.id}">${pantryBadge(x.level||'ok')}</button><button class="buy" data-buy="${x.id}">🛒</button><button class="trash" data-pantrytrash="${x.id}">✕</button></div>`).join('');
const days=state.days.map((d,i)=>{const dt=dateAt(i);return `<article class="day"><div class="dayhead"><div><span>${esc(d.name)}</span><strong>${dt.getDate()}</strong></div><small>${dt.toLocaleDateString('es-ES',{month:'short'})}</small></div>${Object.keys(mealLabels).map(k=>renderMeal(d,i,k)).join('')}<input class="note" data-note="${i}" value="${esc(d.note||'')}" placeholder="Nota del día…"></article>`}).join('');
const viewButtons=`<button class="${viewProfile==='all'?'active':''}" data-view="all">Todos</button>${state.profiles.map(p=>`<button class="${viewProfile===p.id?'active':''}" data-view="${p.id}">${esc(p.name)}</button>`).join('')}`;
const history=state.history.slice(0,8).map(h=>`<div class="historyitem"><strong>${esc(h.actor)}</strong><span>${esc(h.action)}</span><small>${relative(h.at)}</small></div>`).join('')||'<p class="empty">Todavía no hay cambios registrados.</p>';
el.innerHTML=`<main class="shell"><header class="top"><div><p class="eyebrow">FAMILIA LAVIÑA PÉREZ</p><h1>Comemos juntos,<br><em>a nuestra manera.</em></h1></div><div class="headerRight">${profileControls()}<button id="logout" class="icon" title="Salir">↪</button></div></header><nav class="navchips"><a href="#compra">Lista de la compra</a><a href="#despensa">Despensa</a><a href="#planning">Planning</a><a href="#actividad">Actividad</a></nav><div class="sync">${esc(status||`Sincronizado · última edición ${state.updatedBy||'Familia Laviña Pérez'}`)}</div>
<section id="compra" class="shopping first"><div class="intro"><div class="bubble">🛒</div><p class="eyebrow">PRIMERO, LA COMPRA</p><h2>Lo que falta,<br><em>a mano.</em></h2><p>La lista compartida de toda la familia. Todo lo que se cambie queda registrado con el perfil que lo hizo.</p></div><div class="listcard"><div class="listhead"><h3>Lista de la compra</h3><span>${state.shopping.filter(x=>!x.done).length} pendientes</span></div>${list||'<p class="empty">No hay nada pendiente.</p>'}<div class="add"><input id="newItem" placeholder="Añadir producto…"><button id="add">＋</button></div></div></section>
<section id="despensa" class="pantry-section"><div class="pantry-hero"><div class="bubble pantrybubble">🥫</div><div><p class="eyebrow">DESPENSA FAMILIAR</p><h2>Sabemos lo que hay<br><em>antes de comprar.</em></h2><p>Controlad lo que queda en casa y enviad a la lista lo que haga falta.</p></div><div class="pantry-stats"><div><strong>${state.pantry.filter(x=>(x.level||'ok')==='ok').length}</strong><span>Hay</span></div><div><strong>${state.pantry.filter(x=>x.level==='low').length}</strong><span>Poco</span></div><div><strong>${state.pantry.filter(x=>x.level==='out').length}</strong><span>Falta</span></div></div></div><div class="pantrycard"><div class="listhead"><h3>Despensa</h3><span>${state.pantry.length} productos</span></div>${pantry||'<p class="empty">Añade productos habituales.</p>'}<div class="pantryadd"><input id="newPantry" placeholder="Ej. Leche, arroz, café…"><select id="newPantryCat">${pantryCategories.map(c=>`<option>${esc(c)}</option>`).join('')}</select><input id="newPantryQty" placeholder="Cantidad"><button id="addPantry">＋ Añadir</button></div></div></section>
<section id="planning" class="planningWrap"><div class="week"><button id="prev">← anterior</button><div><span>SEMANA</span><strong>${weekLabel()}</strong></div><button id="next">siguiente →</button></div><div class="profileView"><div><p class="eyebrow">VER PLANNING DE</p><div class="profiletabs">${viewButtons}</div></div><p>${viewProfile==='all'?'Ves la comida común y las excepciones individuales.':'Puedes poner una comida distinta para '+esc(profileName(viewProfile))+'. Si la dejas vacía, usará la comida común.'}</p></div><div class="days">${days}</div></section>
<section id="actividad" class="activity"><div><p class="eyebrow">ACTIVIDAD FAMILIAR</p><h2>Quién cambió qué</h2><p>Los cambios importantes quedan asociados al perfil que estaba usando la app.</p></div><div class="historycard">${history}</div></section><footer>Familia Laviña Pérez · compra, despensa y planning personalizados</footer></main>`;bind()}
function renderLogin(){el.innerHTML=`<main class="loginPage"><section class="login"><div class="lock">🔒</div><p class="eyebrow">FAMILIA LAVIÑA PÉREZ</p><h1>Organización familiar</h1><p class="sub">Lista de la compra, despensa y planning individual para cada miembro de la familia.</p><form id="loginForm"><label>Contraseña familiar</label><input id="password" type="password" placeholder="••••••••••" autofocus><p id="err" class="error"></p><button class="primary">Entrar</button></form></section></main>`;document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();const err=document.getElementById('err');err.textContent='';try{await api('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:document.getElementById('password').value})});auth=true;state=null;render();await load()}catch(x){err.textContent=x.message}}}
function bind(){document.getElementById('actor').onchange=e=>{actor=e.target.value;localStorage.setItem('planner-profile',actor);render()};document.getElementById('addProfile').onclick=()=>{const t=document.getElementById('profileName');if(!t.value.trim())return;const p={id:id(),name:t.value.trim()};actor=p.id;localStorage.setItem('planner-profile',actor);save({...state,profiles:[...state.profiles,p]},`creó el perfil ${p.name}`)};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{viewProfile=b.dataset.view;localStorage.setItem('planner-view',viewProfile);render()});document.getElementById('logout').onclick=async()=>{await api('/api/logout',{method:'POST'});auth=false;state=null;render()};document.getElementById('prev').onclick=()=>save({...state,weekOffset:(state.weekOffset||0)-1},'cambió a la semana anterior');document.getElementById('next').onclick=()=>save({...state,weekOffset:(state.weekOffset||0)+1},'cambió a la semana siguiente');
document.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>{const [i,k,pid]=b.dataset.check.split(':');const days=state.days.map((d,j)=>{if(j!=i)return d;const m=d[k];if(pid==='all')return {...d,[k]:{...m,done:!m.done}};return {...d,[k]:{...m,people:{...m.people,[pid]:{text:mealValue(m,pid),done:!mealDone(m,pid)}}}}});save({...state,days},`marcó ${mealLabels[k].toLowerCase()} del ${state.days[i].name}`)});
document.querySelectorAll('[data-meal]').forEach(t=>t.onblur=()=>{const [i,k,pid]=t.dataset.meal.split(':');const days=state.days.map((d,j)=>{if(j!=i)return d;const m=d[k];if(pid==='all')return {...d,[k]:{...m,text:t.value}};return {...d,[k]:{...m,people:{...m.people,[pid]:{...(m.people[pid]||{}),text:t.value,done:mealDone(m,pid)}}}}});save({...state,days},`cambió ${mealLabels[k].toLowerCase()} del ${state.days[i].name}${pid==='all'?' para todos':' para '+profileName(pid)}`)});
document.querySelectorAll('[data-note]').forEach(t=>t.onblur=()=>{const i=t.dataset.note,days=state.days.map((d,j)=>j==i?{...d,note:t.value}:d);save({...state,days},`cambió la nota del ${state.days[i].name}`)});
document.querySelectorAll('[data-shopcheck]').forEach(b=>b.onclick=()=>{const item=state.shopping.find(x=>x.id===b.dataset.shopcheck);save({...state,shopping:state.shopping.map(x=>x.id===b.dataset.shopcheck?{...x,done:!x.done}:x)},`${item?.done?'desmarcó':'compró'} ${item?.text||'un producto'}`)});document.querySelectorAll('[data-shoptext]').forEach(t=>t.onblur=()=>save({...state,shopping:state.shopping.map(x=>x.id===t.dataset.shoptext?{...x,text:t.value}:x)},'editó un producto de la compra'));document.querySelectorAll('[data-trash]').forEach(b=>b.onclick=()=>{const item=state.shopping.find(x=>x.id===b.dataset.trash);save({...state,shopping:state.shopping.filter(x=>x.id!==b.dataset.trash)},`eliminó ${item?.text||'un producto'} de la compra`) });const add=()=>{const t=document.getElementById('newItem');if(!t.value.trim())return;const text=t.value.trim();save({...state,shopping:[...state.shopping,{id:id(),text,done:false}]},`añadió ${text} a la compra`)};document.getElementById('add').onclick=add;document.getElementById('newItem').onkeydown=e=>{if(e.key==='Enter')add()};
document.querySelectorAll('[data-pantrytext]').forEach(t=>t.onblur=()=>save({...state,pantry:state.pantry.map(x=>x.id===t.dataset.pantrytext?{...x,text:t.value}:x)},'editó un producto de despensa'));document.querySelectorAll('[data-pantrycat]').forEach(t=>t.onchange=()=>save({...state,pantry:state.pantry.map(x=>x.id===t.dataset.pantrycat?{...x,category:t.value}:x)},'cambió una categoría de despensa'));document.querySelectorAll('[data-pantryqty]').forEach(t=>t.onblur=()=>save({...state,pantry:state.pantry.map(x=>x.id===t.dataset.pantryqty?{...x,quantity:t.value}:x)},'actualizó una cantidad de despensa'));document.querySelectorAll('[data-stock]').forEach(b=>b.onclick=()=>{const order={ok:'low',low:'out',out:'ok'},item=state.pantry.find(x=>x.id===b.dataset.stock);save({...state,pantry:state.pantry.map(x=>x.id===b.dataset.stock?{...x,level:order[x.level||'ok']}:x)},`actualizó el stock de ${item?.text||'un producto'}`)});document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{const item=state.pantry.find(x=>x.id===b.dataset.buy);if(!item)return;const exists=state.shopping.some(x=>!x.done&&x.text.trim().toLowerCase()===item.text.trim().toLowerCase());save({...state,shopping:exists?state.shopping:[...state.shopping,{id:id(),text:item.text,done:false}],pantry:state.pantry.map(x=>x.id===item.id?{...x,level:'out'}:x)},`mandó ${item.text} a la lista de la compra`)});document.querySelectorAll('[data-pantrytrash]').forEach(b=>b.onclick=()=>{const item=state.pantry.find(x=>x.id===b.dataset.pantrytrash);save({...state,pantry:state.pantry.filter(x=>x.id!==b.dataset.pantrytrash)},`eliminó ${item?.text||'un producto'} de despensa`) });const addPantry=()=>{const t=document.getElementById('newPantry'),c=document.getElementById('newPantryCat'),q=document.getElementById('newPantryQty');if(!t.value.trim())return;const text=t.value.trim();save({...state,pantry:[...state.pantry,{id:id(),text,category:c.value,quantity:q.value.trim(),level:'ok'}]},`añadió ${text} a despensa`)};document.getElementById('addPantry').onclick=addPantry;document.getElementById('newPantry').onkeydown=e=>{if(e.key==='Enter')addPantry()}}
check();setInterval(()=>{if(auth&&state)load(true)},3000);
