(()=>{
let nice=null,tab=localStorage.getItem('nice-tab')||'shopping',busy=false;
const root=()=>document.getElementById('app');
const norm=s=>String(s||'').trim().toLowerCase();
const uid=()=>crypto.randomUUID();
const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const names=['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'];
function monday(offset=0){const d=new Date(),day=d.getDay()||7;d.setHours(12,0,0,0);d.setDate(d.getDate()-day+1+offset*7);return d}
function key(){return monday(nice?.weekOffset||0).toISOString().slice(0,10)}
function weekLabel(){const a=monday(nice?.weekOffset||0),b=new Date(a);b.setDate(a.getDate()+6);const f=d=>new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'short'}).format(d);return `${f(a)} — ${f(b)}`}
function emptyWeek(){return names.map(name=>({name,lunch:'',dinner:'',note:''}))}
function ensure(){nice=nice||{shopping:[],pantry:[],weeks:{},weekOffset:0};nice.shopping=Array.isArray(nice.shopping)?nice.shopping:[];nice.pantry=Array.isArray(nice.pantry)?nice.pantry:[];nice.weeks=nice.weeks&&typeof nice.weeks==='object'?nice.weeks:{};if(!nice.weeks[key()])nice.weeks[key()]=emptyWeek()}
async function api(url,opt){const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Error');return d}
async function load(){if(busy)return;try{nice=await api('/api/nice');ensure();renderNice()}catch{}}
async function save(){busy=true;try{nice=await api('/api/nice',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(nice)});ensure();renderNice()}finally{busy=false}}
function isMarta(){const selected=document.querySelector('.profile-card.selected strong');return selected&&selected.textContent.trim().toLowerCase()==='marta'}
function mount(){const old=document.getElementById('nice-marta');if(!isMarta()){old?.remove();return}if(old)return;if(!nice){load();return}const profile=document.querySelector('.profile-zone');if(!profile)return;const sec=document.createElement('section');sec.id='nice-marta';sec.className='nice-space';profile.insertAdjacentElement('afterend',sec);renderNice()}
function renderNice(){if(!isMarta())return;let sec=document.getElementById('nice-marta');if(!sec){mount();sec=document.getElementById('nice-marta');if(!sec)return}ensure();
const active=nice.weeks[key()];
const shop=nice.shopping.map(x=>`<div class="nice-row"><button data-nice-bought="${x.id}" class="nice-ok">✓</button><span>${esc(x.text)}</span><button data-nice-delshop="${x.id}" class="nice-x">✕</button></div>`).join('')||'<p class="nice-empty">No hay nada pendiente.</p>';
const pantry=nice.pantry.map(x=>`<div class="nice-pantry-row"><span>${esc(x.text)}</span><div class="nice-step"><button data-nice-minus="${x.id}">−</button><b>${x.count||1}</b><button data-nice-plus="${x.id}">＋</button></div><button data-nice-more="${x.id}" class="nice-more">🛒</button><button data-nice-out="${x.id}" class="nice-out">Se acabó</button></div>`).join('')||'<p class="nice-empty">Todavía no hay productos.</p>';
const days=active.map((d,i)=>`<div class="nice-day"><div class="nice-day-head"><strong>${d.name}</strong></div><label>Comida<input data-nice-meal="${i}:lunch" value="${esc(d.lunch||'')}" placeholder="Añadir comida"></label><label>Cena<input data-nice-meal="${i}:dinner" value="${esc(d.dinner||'')}" placeholder="Añadir cena"></label><input class="nice-note" data-nice-note="${i}" value="${esc(d.note||'')}" placeholder="Nota"></div>`).join('');
sec.innerHTML=`<div class="nice-head"><div><p class="eyebrow">MARTA · NIZA 🇫🇷</p><h2>Mi vida en Niza</h2><p>Tu espacio personal, separado del familiar.</p></div><span class="nice-date">Sep 2026 — Mar 2027</span></div><div class="nice-tabs"><button data-nice-tab="shopping" class="${tab==='shopping'?'active':''}">Compra</button><button data-nice-tab="pantry" class="${tab==='pantry'?'active':''}">Despensa</button><button data-nice-tab="planning" class="${tab==='planning'?'active':''}">Planning</button></div><div class="nice-panel">${tab==='shopping'?`<div class="nice-title"><h3>Lista de la compra</h3><span>${nice.shopping.length}</span></div>${shop}<div class="nice-add"><input id="nice-new-shop" placeholder="Añadir producto…"><button id="nice-add-shop">＋</button></div>`:tab==='pantry'?`<div class="nice-title"><h3>Despensa de Niza</h3><span>${nice.pantry.length}</span></div>${pantry}<div class="nice-add"><input id="nice-new-pantry" placeholder="Añadir producto…"><button id="nice-add-pantry">＋</button></div>`:`<div class="nice-week"><button id="nice-prev">←</button><strong>${weekLabel()}</strong><button id="nice-next">→</button></div><div class="nice-days">${days}</div>`}</div>`;
bind()}
function bind(){document.querySelectorAll('[data-nice-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.niceTab;localStorage.setItem('nice-tab',tab);renderNice()});
const addShop=document.getElementById('nice-add-shop');if(addShop){const fn=()=>{const i=document.getElementById('nice-new-shop'),text=i.value.trim();if(!text||nice.shopping.some(x=>norm(x.text)===norm(text)))return;nice.shopping.push({id:uid(),text});save()};addShop.onclick=fn;document.getElementById('nice-new-shop').onkeydown=e=>{if(e.key==='Enter')fn()}}
const addPantry=document.getElementById('nice-add-pantry');if(addPantry){const fn=()=>{const i=document.getElementById('nice-new-pantry'),text=i.value.trim();if(!text)return;const ex=nice.pantry.find(x=>norm(x.text)===norm(text));if(ex)ex.count=(ex.count||1)+1;else nice.pantry.push({id:uid(),text,count:1});save()};addPantry.onclick=fn;document.getElementById('nice-new-pantry').onkeydown=e=>{if(e.key==='Enter')fn()}}
document.querySelectorAll('[data-nice-bought]').forEach(b=>b.onclick=()=>{const x=nice.shopping.find(y=>y.id===b.dataset.niceBought);if(!x)return;nice.shopping=nice.shopping.filter(y=>y.id!==x.id);const ex=nice.pantry.find(y=>norm(y.text)===norm(x.text));if(ex)ex.count=(ex.count||1)+1;else nice.pantry.push({id:uid(),text:x.text,count:1});save()});
document.querySelectorAll('[data-nice-delshop]').forEach(b=>b.onclick=()=>{nice.shopping=nice.shopping.filter(x=>x.id!==b.dataset.niceDelshop);save()});
document.querySelectorAll('[data-nice-minus]').forEach(b=>b.onclick=()=>{const x=nice.pantry.find(y=>y.id===b.dataset.niceMinus);if(!x)return;x.count=(x.count||1)-1;if(x.count<=0){nice.pantry=nice.pantry.filter(y=>y.id!==x.id);if(!nice.shopping.some(y=>norm(y.text)===norm(x.text)))nice.shopping.push({id:uid(),text:x.text})}save()});
document.querySelectorAll('[data-nice-plus]').forEach(b=>b.onclick=()=>{const x=nice.pantry.find(y=>y.id===b.dataset.nicePlus);if(x){x.count=(x.count||1)+1;save()}});
document.querySelectorAll('[data-nice-more]').forEach(b=>b.onclick=()=>{const x=nice.pantry.find(y=>y.id===b.dataset.niceMore);if(x&&!nice.shopping.some(y=>norm(y.text)===norm(x.text))){nice.shopping.push({id:uid(),text:x.text});save()}});
document.querySelectorAll('[data-nice-out]').forEach(b=>b.onclick=()=>{const x=nice.pantry.find(y=>y.id===b.dataset.niceOut);if(!x)return;nice.pantry=nice.pantry.filter(y=>y.id!==x.id);if(!nice.shopping.some(y=>norm(y.text)===norm(x.text)))nice.shopping.push({id:uid(),text:x.text});save()});
if(document.getElementById('nice-prev'))document.getElementById('nice-prev').onclick=()=>{nice.weekOffset=(nice.weekOffset||0)-1;ensure();save()};if(document.getElementById('nice-next'))document.getElementById('nice-next').onclick=()=>{nice.weekOffset=(nice.weekOffset||0)+1;ensure();save()};
document.querySelectorAll('[data-nice-meal]').forEach(i=>i.onchange=()=>{const [d,k]=i.dataset.niceMeal.split(':');nice.weeks[key()][+d][k]=i.value;save()});document.querySelectorAll('[data-nice-note]').forEach(i=>i.onchange=()=>{nice.weeks[key()][+i.dataset.niceNote].note=i.value;save()})}
let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(mount,60)}).observe(root(),{childList:true,subtree:true});mount();
})();
